"""
Type stubs for phase1_10_00_phase1_protocols.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from collections.abc import Generator
from pathlib import Path
from typing import Any, Protocol

class PDFExtractorProtocol(Protocol):
    """Protocol for PDF text extraction implementations."""
    def extract_text_stream(self) -> Generator[str, None, None]: ...
    def extract_with_limit(self, char_limit: int) -> tuple[str, int, int]: ...

class TruncationAuditProtocol(Protocol):
    """Protocol for truncation audit records."""
    total_chars: int
    processed_chars: int
    chars_lost: int
    loss_ratio: float
    limit_applied: int
    was_truncated: bool
    def to_dict(self) -> dict[str, Any]: ...
    def log_if_truncated(self) -> None: ...

class ChunkProtocol(Protocol):
    """Protocol for chunk representations."""
    chunk_id: str
    policy_area_id: str
    dimension_id: str
    text: str
    assignment_method: str
    semantic_confidence: float

class Phase1ExecutorProtocol(Protocol):
    """Protocol for Phase 1 execution."""
    def execute(self, pdf_path: Path) -> list[Any]: ...
