"""
Type stubs for phase0_to_phase1_bridge.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Optional
import hashlib

class Phase0OutputContract:
    """Contract defining expected Phase 0 output structure."""
    document_path: str
    document_hash: str
    questionnaire_hash: str
    preprocessed_text: Optional[str]
    validation_passed: bool
    pdm_profile: Optional[Any] = None
    signal_registry: Optional[Any] = None
    seed: int = 42

class Phase0ToPhase1BridgeError(Exception):
    """Raised when Phase 0 → Phase 1 bridge transformation fails."""
    ...

def extract_from_wiring_components(wiring: Any) -> Phase0OutputContract: ...
def transform_to_canonical_input(phase0_output: Phase0OutputContract) -> Any: ...
def bridge_phase0_to_phase1(wiring: Any) -> Any: ...
def _compute_document_hash(document_path: str) -> str: ...

__all__ = ['Phase0OutputContract', 'Phase0ToPhase1BridgeError', 'bridge_phase0_to_phase1', 'extract_from_wiring_components', 'transform_to_canonical_input']
