"""
Type stubs for phase1_10_00_phase1_types.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from typing import Any, NotRequired, TypedDict

class TruncationAuditDict(TypedDict):
    """Serialized form of TruncationAudit."""
    total_chars: int
    processed_chars: int
    chars_lost: int
    loss_ratio: float
    limit_applied: int
    was_truncated: bool

class SubphaseResultDict(TypedDict):
    """Result from a single subphase execution."""
    subphase_id: int
    success: bool
    output: Any
    error: NotRequired[str]

class ChunkTraceability(TypedDict):
    """Traceability metadata for chunk assignment."""
    assignment_method: str
    semantic_confidence: float
