"""
Type stubs for phase1_04_00_phase_protocol.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
import hashlib
import json
from abc import ABC, abstractmethod
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Generic, TypeVar

class PhaseInvariant:
    """An invariant that must hold for a phase."""
    name: str
    description: str
    check: callable
    error_message: str

class PhaseMetadata:
    """Metadata for a phase execution."""
    phase_name: str
    started_at: str
    finished_at: str | None = None
    duration_ms: float | None = None
    success: bool = False
    error: str | None = None

class ContractValidationResult:
    """Result of validating a contract."""
    passed: bool
    contract_type: str
    phase_name: str
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    validation_timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

class PhaseContract(ABC, Generic[TInput, TOutput]):
    """Abstract base class for phase contracts."""
    def __init__(self, phase_name: str): ...
    @abstractmethod
    def validate_input(self, input_data: Any) -> ContractValidationResult: ...
    @abstractmethod
    def validate_output(self, output_data: Any) -> ContractValidationResult: ...
    def add_invariant(self, name: str, description: str, check: callable, error_message: str) -> None: ...
    def check_invariants(self, data: Any) -> tuple[bool, list[str]]: ...

class PhaseArtifact:
    """An artifact produced by a phase."""
    artifact_name: str
    artifact_path: Path
    sha256: str
    size_bytes: int
    created_at: str

class PhaseManifestBuilder:
    """Builds the phase-explicit section of the verification manifest."""
    def __init__(self): ...
    def record_phase(self, phase_name: str, metadata: PhaseMetadata, input_validation: ContractValidationResult, output_validation: ContractValidationResult, invariants_checked: list[str], artifacts: list[PhaseArtifact]) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def save(self, output_path: Path) -> None: ...

def compute_contract_hash(contract_data: Any) -> str: ...

__all__ = ['ContractValidationResult', 'PhaseArtifact', 'PhaseContract', 'PhaseInvariant', 'PhaseManifestBuilder', 'PhaseMetadata', 'compute_contract_hash']
