"""
Type stubs for phase1_08_00_adapter.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from types import MappingProxyType
from typing import Any, Final
from farfan_pipeline.calibration.parameters import ParameterLoaderV2
from farfan_pipeline.core.types import ChunkData, PreprocessedDocument, Provenance

_EMPTY_MAPPING: Final[MappingProxyType[str, Any]] = MappingProxyType({})
_VALID_CHUNK_TYPES: Final[frozenset[str]] = frozenset({'diagnostic', 'activity', 'indicator', 'resource', 'temporal', 'entity'})

class ChunkArtifacts:
    """Immutable container for all outputs produced by processing a single chunk."""
    sentence: dict[str, Any]
    sentence_metadata: dict[str, Any]
    chunk_summary: dict[str, Any]
    chunk_data: ChunkData
    table: dict[str, Any] | None
    entity_mentions: dict[str, list[int]]
    temporal_mentions: dict[str, list[int]]
    chunk_text_length: int
    has_provenance: bool

class CPPAdapterError(Exception):
    """Raised when CPP to PreprocessedDocument conversion fails."""
    ...

class CPPAdapter:
    """Adapter to convert CanonPolicyPackage (CPP output) to PreprocessedDocument."""
    _PARAMETER_CONTEXT: Final[str] = 'farfan_core.utils.cpp_adapter.CPPAdapter.__init__'
    def __init__(self, enable_runtime_validation: bool) -> None: ...
    def _build_config(self) -> dict[str, Any]: ...
    def _resolve_chunk_attributes(self, chunk: Any) -> dict[str, Any]: ...
    def _validate_provenance(self, provenance: Any, chunk_id: str) -> None: ...
    def _build_confidence_dict(self, confidence: Any) -> dict[str, float]: ...
    def _process_chunk(self, chunk: Any, idx: int, current_offset: int) -> ChunkArtifacts: ...
    def _validate_canon_package(self, canon_package: Any, document_id: str) -> None: ...
    def _validate_chunk_cardinality_and_metadata(self, sorted_chunks: list[Any]) -> None: ...
    def _build_quality_metrics(self, canon_package: Any) -> dict[str, float]: ...
    def _build_policy_manifest(self, canon_package: Any) -> dict[str, list[Any]] | None: ...
    def _validate_runtime_contract(self, preprocessed_doc: PreprocessedDocument, metadata_dict: dict[str, Any]) -> None: ...
    def to_preprocessed_document(self, canon_package: Any, document_id: str) -> PreprocessedDocument: ...

def adapt_cpp_to_orchestrator(canon_package: Any, document_id: str) -> PreprocessedDocument: ...

__all__ = ['CPPAdapter', 'CPPAdapterError', 'ChunkArtifacts', 'adapt_cpp_to_orchestrator']
