"""
Type stubs for phase6_to_phase7_bridge.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, List, Optional

EXPECTED_CLUSTER_COUNT = 4
EXPECTED_CLUSTER_IDS = frozenset({'CLUSTER_MESO_1', 'CLUSTER_MESO_2', 'CLUSTER_MESO_3', 'CLUSTER_MESO_4'})
MIN_SCORE = 0.0
MAX_SCORE = 3.0
CLUSTER_COMPOSITION = {'CLUSTER_MESO_1': ['PA01', 'PA02', 'PA03'], 'CLUSTER_MESO_2': ['PA04', 'PA05', 'PA06'], 'CLUSTER_MESO_3': ['PA07', 'PA08'], 'CLUSTER_MESO_4': ['PA09', 'PA10']}

class Phase6OutputContract:
    """Contract defining expected Phase 6 output structure."""
    cluster_count: int
    cluster_ids: frozenset[str]
    cluster_scores: Dict[str, float]
    cluster_coherence: Dict[str, float]
    validation_passed: bool
    provenance_nodes: List[str]
    certificate: Dict[str, Any]
    min_score: float = 0.0
    max_score: float = 3.0

class Phase6ToPhase7BridgeError(Exception):
    """Raised when Phase 6 → Phase 7 bridge transformation fails."""
    def __init__(self, message: str, error_code: str, context: Optional[Dict[str, Any]]): ...

def extract_from_cluster_scores(cluster_scores: List['ClusterScore']) -> Phase6OutputContract: ...
def validate_phase6_output_for_phase7(cluster_scores: List['ClusterScore']) -> tuple[bool, Dict[str, Any]]: ...
def bridge_phase6_to_phase7(cluster_scores: List['ClusterScore']) -> tuple[List['ClusterScore'], Phase6OutputContract]: ...

__all__ = ['Phase6OutputContract', 'Phase6ToPhase7BridgeError', 'bridge_phase6_to_phase7', 'extract_from_cluster_scores', 'validate_phase6_output_for_phase7', 'EXPECTED_CLUSTER_COUNT', 'EXPECTED_CLUSTER_IDS', 'MIN_SCORE', 'MAX_SCORE', 'CLUSTER_COMPOSITION']
