"""
Type stubs for wiring_types.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
import os
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any, Protocol

class Severity(str, Enum):
    """Violation severity levels."""
    ...

class ContractViolation:
    """Represents a single contract violation detected during validation."""
    type: str
    severity: Severity
    component_path: str
    message: str
    expected: Any = None
    actual: Any = None
    remediation: str = ''
    timestamp: datetime = field(default_factory=datetime.utcnow)
    def to_dict(self) -> dict[str, Any]: ...
    def format_console(self) -> str: ...

class ValidationResult:
    """Result of WiringValidator.validate() call."""
    passed: bool
    violations: list[ContractViolation] = field(default_factory=list)
    integrity_hash: str = ''
    validation_time_ms: float = 0.0
    @property
    def critical_count(self) -> int: ...
    @property
    def high_count(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def format_console(self) -> str: ...

class WiringFeatureFlags:
    """Feature flags for wiring configuration."""
    enable_http_signals: bool = False
    enable_calibration: bool = False
    strict_validation: bool = True
    memory_signal_ttl: int = 3600
    enable_resource_enforcement: bool = False
    @classmethod
    def from_env(cls) -> WiringFeatureFlags: ...
    def validate(self) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...

class WiringComponents:
    """Container for all wired components."""
    provider: QuestionnaireResourceProvider
    signal_client: SignalClient
    signal_registry: SignalRegistry
    executor_config: ExecutorConfig
    factory: CoreModuleFactory
    arg_router: ExtendedArgRouter
    class_registry: dict[str, type]
    validator: WiringValidator
    flags: WiringFeatureFlags
    calibration_orchestrator: Any | None = None
    init_hashes: dict[str, str] = field(default_factory=dict)

class TierValidator(Protocol):
    """Protocol for tier-specific validators."""
    def validate(self, wiring: WiringComponents) -> list[ContractViolation]: ...
