"""
Type stubs for phase1_phase2_adapter.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Final, Protocol, runtime_checkable

DEFAULT_SCHEMA_VERSION: Final[str] = 'CPP-2025.1'
ADAPTER_VERSION: Final[str] = '1.0.0'

class Phase1OutputProtocol(Protocol):
    """Protocol for Phase 1 output structure."""
    @property
    def enriched_signal_packs(self) -> dict[str, Any]: ...
    @property
    def irrigation_map(self) -> Any: ...
    @property
    def smart_chunks(self) -> list[Any]: ...
    @property
    def truncation_audit(self) -> Any: ...
    @property
    def structural_validation_result(self) -> Any: ...
    @property
    def questionnaire_mapper(self) -> Any | None: ...

class Phase2InputBundle:
    """Immutable bundle adapted from Phase 1 output."""
    chunks: list[Any]
    schema_version: str
    enriched_signal_packs: dict[str, Any] = field(default_factory=dict)
    irrigation_map: Any = None
    truncation_audit: Any = None
    structural_validation: Any = None
    questionnaire_mapper: Any = None
    adaptation_source: str = 'Phase1Output'
    adaptation_version: str = '1.0.0'

def extract_chunks(phase1_output: Any) -> list[Any]: ...
def extract_schema_version(phase1_output: Any) -> str: ...
def adapt_phase1_to_phase2(phase1_output: Any) -> Phase2InputBundle: ...
def validate_adaptation(original: Any, adapted: Phase2InputBundle) -> tuple[bool, list[str]]: ...

__all__ = ['Phase1OutputProtocol', 'Phase2InputBundle', 'adapt_phase1_to_phase2', 'validate_adaptation', 'extract_chunks', 'extract_schema_version', 'DEFAULT_SCHEMA_VERSION', 'ADAPTER_VERSION']
