"""
Type stubs for phase2_phase3_adapter.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Final, Protocol, runtime_checkable

ADAPTER_VERSION: Final[str] = '1.0.0'
QUESTIONS_PER_DIMENSION: Final[int] = 5
TOTAL_DIMENSIONS: Final[int] = 6
TOTAL_POLICY_AREAS: Final[int] = 10
QUESTIONS_PER_PA: Final[int] = QUESTIONS_PER_DIMENSION * TOTAL_DIMENSIONS
PHASE2_QID_PATTERN: Final[re.Pattern] = re.compile('^Q(\\d{3})_PA(\\d{2})$')
PHASE3_QID_PATTERN: Final[re.Pattern] = re.compile('^PA(\\d{2})-DIM(\\d{2})-Q(\\d{3})$')

class Phase2ResultProtocol(Protocol):
    """Protocol for Phase 2 result structure."""
    @property
    def question_id(self) -> str: ...
    @property
    def policy_area(self) -> str: ...
    @property
    def narrative(self) -> str: ...
    @property
    def evidence(self) -> dict[str, Any]: ...
    @property
    def confidence_score(self) -> float: ...
    @property
    def provenance(self) -> dict[str, Any]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...

class MicroQuestionRun:
    """Phase 3 input structure: MicroQuestionRun."""
    question_id: str
    question_global: int
    base_slot: str
    evidence: dict[str, Any] | None
    metadata: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    duration_ms: float | None = None
    aborted: bool = False
    _adapted_from: str | None = field(default=None, compare=False)
    _adapter_version: str = field(default=ADAPTER_VERSION, compare=False)

class AdaptationResult:
    """Result of Phase 2 → Phase 3 adaptation."""
    micro_runs: list[MicroQuestionRun]
    success_count: int
    error_count: int
    warnings: list[str]
    adaptation_timestamp: datetime = field(default_factory=datetime.now)
    def to_dict(self) -> dict[str, Any]: ...

def parse_phase2_question_id(question_id: str) -> tuple[int, int]: ...
def derive_dimension(q_base: int) -> int: ...
def derive_question_in_dimension(q_base: int) -> int: ...
def derive_base_slot(q_base: int) -> str: ...
def derive_question_global(q_base: int, pa_num: int) -> int: ...
def transform_question_id(phase2_qid: str) -> str: ...
def reverse_transform_question_id(phase3_qid: str) -> str: ...
def adapt_single_result(result: Any, inject_confidence: bool) -> MicroQuestionRun: ...
def adapt_phase2_to_phase3(phase2_output: Any, inject_confidence: bool) -> AdaptationResult: ...
def validate_adaptation(original_count: int, adapted: AdaptationResult) -> tuple[bool, list[str]]: ...

__all__ = ['Phase2ResultProtocol', 'MicroQuestionRun', 'AdaptationResult', 'parse_phase2_question_id', 'derive_dimension', 'derive_question_in_dimension', 'derive_base_slot', 'derive_question_global', 'transform_question_id', 'reverse_transform_question_id', 'adapt_single_result', 'adapt_phase2_to_phase3', 'validate_adaptation', 'ADAPTER_VERSION', 'PHASE2_QID_PATTERN', 'PHASE3_QID_PATTERN']
