"""
Type stubs for phase5_10_00_exit_contract.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
import logging
from typing import Any
from farfan_pipeline.phases.Phase_05.phase5_10_00_area_aggregation import AreaScore
from farfan_pipeline.phases.Phase_05.PHASE_5_CONSTANTS import CLUSTER_ASSIGNMENTS, DIMENSIONS_PER_AREA, EXPECTED_AREA_SCORE_COUNT, MAX_SCORE, MIN_SCORE, POLICY_AREAS
from farfan_pipeline.phases.Phase_05.primitives.phase5_00_00_types import AggregationStrategy

class Phase5ExitContract:
    """Exit contract validator for Phase 5."""
    @classmethod
    def validate(cls, area_scores: list[AreaScore]) -> tuple[bool, dict[str, Any]]: ...

def validate_phase5_exit(area_scores: list[AreaScore]) -> tuple[bool, dict[str, Any]]: ...

__all__ = ['Phase5ExitContract', 'validate_phase5_exit']
