"""
Type stubs for phase3_05_00_nexus_interface_validator.py

Auto-generated by stub_generator.py
Do not edit manually - changes will be overwritten
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Any

class ValidationResult:
    """Result of interface validation."""
    is_valid: bool
    errors: list[str]
    warnings: list[str]
    metadata: dict[str, Any]
    def to_dict(self) -> dict[str, Any]: ...

class NexusScoringValidator:
    """Validates interface contract between Phase 2 (Nexus) and Phase 3 (Scoring)."""
    @classmethod
    def validate_nexus_output(cls, micro_question_run: dict[str, Any]) -> ValidationResult: ...
    @classmethod
    def validate_scoring_context(cls, scoring_context: dict[str, Any] | None) -> ValidationResult: ...
    @classmethod
    def validate_phase_transition(cls, micro_question_run: dict[str, Any], scoring_context: dict[str, Any] | None) -> ValidationResult: ...

class BatchValidator:
    """Validates multiple phase transitions for comprehensive testing."""
    @classmethod
    def validate_batch(cls, micro_question_runs: list[dict[str, Any]], scoring_contexts: list[dict[str, Any] | None] | None) -> dict[str, Any]: ...
